version: '3.8'

services:
  wildfly:
    image: javicook:1.0
    container_name: wildfly
    ports:
      - "8081:8080" 
    volumes:
      - ./wildfly-25.0.1.Final/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./wildfly-25.0.1.Final/modules/system/layers/base:/opt/jboss/wildfly/modules/system/layers/base
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
      - ./target/JaviCook-1.0-SNAPSHOT/img/fotos:/opt/jboss/src/main/webapp/img/fotos  # Volumen para las imágenes subidas en el sv
      - img-data:/opt/jboss/src/main/webapp/img/fotos  # Volumen persistente para imágenes
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=recetas
      - MYSQL_USER=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "" # Contraseña vacía o asigna una contraseña si prefieres
      MYSQL_DATABASE: recetas
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Esto permite la contraseña vacía
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./recetas.sql:/docker-entrypoint-initdb.d/recetas.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
  img-data:  # Definición del volumen persistente para las imágenes
